DROP TABLE IF EXISTS users;

CREATE TABLE users(
    users_id SERIAL PRIMARY KEY,
	firstname VARCHAR(50),
	lastname VARCHAR(50)
)

ALTER TABLE users
ADD COLUMN IF NOT EXISTS isadmin INTEGER;

ALTER TABLE users
ALTER COLUMN isadmin TYPE BOOLEAN
USING isadmin::BOOLEAN;

ALTER TABLE users
ALTER COLUMN isadmin SET DEFAULT FALSE;

CREATE TABLE tasks (
    id SERIAL PRIMARY KEY,
	name VARCHAR(50),
	user_id INTEGER
)

DROP TABLE tasks;

DROP DATABASE lab1;
